# prefix
unbind c-b
set -g prefix `
bind ` send-prefix

# mouse
set -g mouse on
set -g pane-border-lines heavy
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:cstyle"
set -as terminal-features ",*:RGB"
set -g focus-events on
set -g status off
set -g history-limit 100000
set -sg escape-time 10

set -g detach-on-destroy off

# vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind K resize-pane -U 5
bind J resize-pane -D 5
bind L resize-pane -L 5
bind H resize-pane -R 5

bind r source-file ~/.config/tmux/tmux.conf \; display "config reloaded"

bind b previous-window

bind g display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "lazygit"

# bind C-n display-popup -E 'bash -i -c "read -p \"Session name: \" name; tmux new-session -d -s \$name && tmux switch-client -t \$name"'

# bind C-j display-popup -E 'set session (tmux list-sessions -F "#{session_name}" | grep -vx "#{session_name}" | fzf --reverse); if test -n "$session"; tmux switch-client -t "$session"; end'

# Replace the default 's' menu with a supercharged fzf popup
# bind s display-popup -w 50% -h 50% -E "tmux list-sessions -F '#{session_name}' | fzf --reverse --header 'Enter: Switch | Ctrl-x: Kill' --bind 'ctrl-x:execute-silent(tmux kill-session -t {})+reload(tmux list-sessions -F \"##{session_name}\")' | xargs -r -I {} tmux switch-client -t {}"

# Supercharged s menu (Create, Switch, Kill, Preview)
bind s display-popup -w 80% -h 80% -E "bash $HOME/.config/tmux/scripts/session.sh"

bind t display-popup \
  -d "#{pane_current_path}" \
  -w 75% \
  -h 75% \
  -E "fish"

bind e new-window -c "#{pane_current_path}" -n "yazi" "fish -c yazi"

# set -g @resurrect-processes ':all:'
set -g @resurrect-processes 'btop yazi ~hx'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
run '~/.config/tmux/plugins/tpm/tpm'
