# prefix
unbind c-b
set -g prefix `
bind ` send-prefix

# mouse
set -g mouse on
set -g pane-border-lines heavy
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:cstyle"
set -as terminal-features ",*:RGB"
set -g focus-events on
set -g status off
set -g history-limit 100000
set -sg escape-time 10
bind r source-file ~/.config/tmux/tmux.conf \; display "config reloaded"

# vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind K resize-pane -U 5
bind J resize-pane -D 5
bind L resize-pane -L 5
bind H resize-pane -R 5

bind b previous-window

bind C-y display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "lazygit"

bind C-n display-popup -E 'bash -i -c "read -p \"Session name: \" name; tmux new-session -d -s \$name && tmux switch-client -t \$name"'

bind C-j display-popup -E 'set session (tmux list-sessions -F "##{session_name}" | grep -vx "#{session_name}" | fzf --reverse); if test -n "$session"; tmux switch-client -t "$session"; end'

bind C-t display-popup \
  -d "#{pane_current_path}" \
  -w 75% \
  -h 75% \
  -E "fish"

bind C-f new-window -c "#{pane_current_path}" -n "yazi" "fish -c yazi"

set -g @resurrect-processes ':all:'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
run '~/.config/tmux/plugins/tpm/tpm'
