# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
# "$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio          = [ 1, 2, 3 ]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
sort_translit  = false
linemode       = "size"
show_hidden    = true
show_symlink   = true
scrolloff      = 5
mouse_events   = [ "click", "scroll", "touch", "move", "drag" ]

[preview]
wrap            = "yes"
tab_size        = 2
max_width       = 9000
max_height      = 19000
cache_dir       = "~/.cache/yazi/cache/"
image_delay     = 0

# [opener]
# edit = [
#   { run = "hx %s", block = true, for = "unix" },
# ]

# [open]
# rules = [
#   { mime = "*", use = [ "edit" ] },
# ]
